### ISSUE TITLE
Installation only to C drive

### ISSUE THREAD

**Issue by BatataDouce** [AvenCores/RCO-Reborn#1]
If someone has Roblox installed for all users and they have a different drive letter (like D) the installation would mostly likely fail. Can be fixed by using "%cd:~0,2%" instead of "c:" for getting the drive letter.

**Comment by AvenCores** [comment]
Your patch has been applied, thanks for using RCO Reborn!

You can download the new version at this link: https://github.com/AvenCores/RCO-Reborn/releases/tag/V1.0.1.
